name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Setup Node with caching for npm
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Lint
      - name: Lint
        run: npm run lint

      # 5) Test with coverage
      - name: Test (with coverage)
        run: npm test -- --coverage

      # 6) Upload coverage folder as an artifact (viewable in Actions UI)
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage
